package btwmods.stats;

public enum Type {
	MOB_SPAWNING,
	BLOCK_UPDATE,
	ENTITIES_SECTION,
	BUILD_ACTIVE_CHUNKSET,
	CHECK_PLAYER_LIGHT,
	TIME_SYNC,
	ENTITY_UPDATE,
	TILE_ENTITY_UPDATE,
	MOOD_LIGHT_AND_WEATHER,
	LIGHTNING_AND_RAIN,
	ENTITIES_REMOVE,
	WEATHER_EFFECTS,
	ENTITIES_REGULAR,
	ENTITIES_TILE,
	ENTITIES_TILEPENDING,
	UPDATE_TRACKED_ENTITY_PLAYER_LISTS,
	UPDATE_PLAYER_ENTITIES,
	UPDATE_TRACKED_ENTITY_PLAYER_LIST
}
